server/build.gradle
server/src/main/java/gohome/dailydaily/domain/cart/entity/Cart.java
server/src/main/java/gohome/dailydaily/domain/like/entity/Like.java
server/src/main/java/gohome/dailydaily/domain/member/entity/Member.java
server/src/main/java/gohome/dailydaily/domain/member/entity/Seller.java
server/src/main/java/gohome/dailydaily/domain/order/entity/Order.java
server/src/main/java/gohome/dailydaily/domain/product/entity/Product.java
server/src/main/java/gohome/dailydaily/domain/review/entity/Review.java

어떤 종류의 PR인가요?
- 연관관계 매핑 수정
- dependency 추가

[BE] 연관관계 매핑 수정

---

server/src/main/java/gohome/dailydaily/global/error/BusinessLogicException.java
server/src/main/java/gohome/dailydaily/global/error/ErrorResponse.java
server/src/main/java/gohome/dailydaily/global/error/ExceptionCode.java
server/src/main/java/gohome/dailydaily/global/error/GlobalExceptionAdvice.java

어떤 종류의 PR인가요?
- Controller 단에서 발생하는 예외 처리
- ErrorResponse
예외 발생시 예외 메시지로 전달할 내용을 담고있는 클래스
- GlobalExceptionAdvice
Controller 단에서 발생하는 예외를 한번에 처리해주는 클래스
- Service 로직에서 발생하는 예외 처리
- BusinessLogicException
서비스 계층에서 발생하는 다양한 예외를 처리하기 위한 클래스
- ExceptionCode
의도적으로 예외를 던져야 하는 상황에서 ExceptionCode 에 담긴 예외메시지 정보를 이용해 예외 전달
- HttpRequestMethodNotSupportedException 처리
-

✨ feat : Exception 처리 기능 구현

---

server/build.gradle
server/src/main/java/gohome/dailydaily/domain/member/controller/MemberController.java
server/src/main/java/gohome/dailydaily/domain/member/entity/Member.java
server/src/main/java/gohome/dailydaily/domain/member/entity/MemberRole.java
server/src/main/java/gohome/dailydaily/domain/member/repository/MemberRepository.java
server/src/main/java/gohome/dailydaily/global/common/security/config/SecurityConfig.java
server/src/main/java/gohome/dailydaily/global/common/security/controller/LoginController.java
server/src/main/java/gohome/dailydaily/global/common/security/dto/LoginDto.java
server/src/main/java/gohome/dailydaily/global/common/security/filter/CustomFilterConfigurer.java
server/src/main/java/gohome/dailydaily/global/common/security/filter/JwtAuthenticationFilter.java
server/src/main/java/gohome/dailydaily/global/common/security/filter/JwtVerificationFilter.java
server/src/main/java/gohome/dailydaily/global/common/security/handler/CustomAccessDeniedHandler.java
server/src/main/java/gohome/dailydaily/global/common/security/handler/CustomAuthenticationEntryPoint.java
server/src/main/java/gohome/dailydaily/global/common/security/handler/CustomAuthenticationFailureHandler.java
server/src/main/java/gohome/dailydaily/global/common/security/handler/CustomAuthenticationSuccessHandler.java
server/src/main/java/gohome/dailydaily/global/common/security/handler/ErrorResponder.java
server/src/main/java/gohome/dailydaily/global/common/security/provider/CustomAuthenticationProvider.java
server/src/main/java/gohome/dailydaily/global/common/security/resolver/MemberId.java
server/src/main/java/gohome/dailydaily/global/common/security/resolver/MemberIdResolver.java
server/src/main/java/gohome/dailydaily/global/common/security/util/CustomAuthorityUtils.java
server/src/main/java/gohome/dailydaily/global/common/security/util/CustomUserDetails.java
server/src/main/java/gohome/dailydaily/global/common/security/util/JwtTokenizer.java
server/src/main/java/gohome/dailydaily/global/config/WebConfig.java
server/src/main/resources/application.yml

어떤 종류의 PR인가요?
Issue Number: #5, #6 
- JWT 토큰 생성
- JWT 토큰 검증
- Resolver로 회원 아이디 불러오는 애너테이션 구현
- 유저 로그인
-

✨ feat : JWT 토큰 인증 / 로그인

---

server/src/main/java/gohome/dailydaily/global/common/security/controller/RefreshController.java
server/src/main/java/gohome/dailydaily/global/common/security/dto/RefreshDto.java
server/src/main/java/gohome/dailydaily/global/common/security/filter/CustomFilterConfigurer.java
server/src/main/java/gohome/dailydaily/global/common/security/filter/JwtVerificationFilter.java
server/src/main/java/gohome/dailydaily/global/common/security/filter/RefreshVerificationFilter.java
server/src/main/java/gohome/dailydaily/global/common/security/handler/CustomAuthenticationEntryPoint.java
server/src/main/java/gohome/dailydaily/global/common/security/provider/CustomAuthenticationProvider.java

어떤 종류의 PR인가요?
Issue Number: #34 
- JWT 예외처리
- RefreshToken 으로 AccessToken 재발급
-

✨ feat : RefreshToken 검증 및 재발급

---

server/src/docs/asciidoc/index.adoc
server/src/main/java/gohome/dailydaily/domain/member/controller/MemberController.java
server/src/main/java/gohome/dailydaily/domain/member/dto/MemberDto.java
server/src/main/resources/static/docs/index.html
server/src/test/java/gohome/dailydaily/domain/member/controller/MemberControllerTest.java
server/src/test/java/gohome/dailydaily/util/TestConstant.java
server/src/test/java/gohome/dailydaily/util/security/WithMockCustomUserSecurityContextFactory.java

어떤 종류의 PR인가요?
Issue Number: #44 
- 회원 정보 조회
- Test 코드 리팩토링
- MemberControllerTest > signup 수정
- API 문서 갱신

✨ feat : 회원 정보 조회 기능 추가

---

server/src/main/java/gohome/dailydaily/domain/review/controller/ReviewController.java
server/src/main/java/gohome/dailydaily/domain/review/dto/ReviewDto.java
server/src/main/java/gohome/dailydaily/domain/review/entity/Review.java
server/src/main/java/gohome/dailydaily/domain/review/mapper/ReviewMapper.java
server/src/main/java/gohome/dailydaily/domain/review/repository/ReviewRepository.java
server/src/main/java/gohome/dailydaily/domain/review/service/ReviewService.java
server/src/main/java/gohome/dailydaily/global/error/ExceptionCode.java
server/src/main/java/gohome/dailydaily/global/error/GlobalExceptionAdvice.java

어떤 종류의 PR인가요?
Issue Number: #8 
- 리뷰 등록
- 리뷰 수정
- 리뷰 삭제
- 별점 반영 코드 추가 필요
- 리뷰 관련 기능 테스트 필요

✨ feat : 리뷰 관련 기능 추가

---

server/src/docs/asciidoc/index.adoc
server/src/main/java/gohome/dailydaily/domain/cart/controller/CartController.java
server/src/main/java/gohome/dailydaily/domain/cart/dto/ProductCartDto.java
server/src/main/java/gohome/dailydaily/domain/cart/mapper/ProductCartMapper.java
server/src/main/java/gohome/dailydaily/domain/cart/repository/ProductCartRepository.java
server/src/main/java/gohome/dailydaily/domain/cart/service/CartService.java
server/src/main/java/gohome/dailydaily/global/error/ExceptionCode.java
server/src/main/resources/static/docs/index.html
server/src/test/java/gohome/dailydaily/domain/cart/controller/CartControllerTest.java
server/src/test/java/gohome/dailydaily/domain/cart/service/CartServiceTest.java
server/src/test/java/gohome/dailydaily/util/TestConstant.java

어떤 종류의 PR인가요?
Issue Number: #10 
- 장바구니 상품삭제 API 문서 구현
- 장바구니 상품추가 메서드명 수정
- ProductCartDto.Response 에 productId 추가
-

✨ feat : 장바구니 상품 삭제 기능 구현 및 API 문서화

---

server/src/main/resources/application-server.yml
server/src/main/resources/application.yml

어떤 종류의 PR인가요?
- application-server.yml 배포파일 생성
-

💚 chore : AWS 배포파일 생성

---

server/src/main/java/gohome/dailydaily/domain/review/dto/ReviewDto.java
server/src/main/java/gohome/dailydaily/domain/review/mapper/ReviewMapper.java
server/src/main/java/gohome/dailydaily/global/common/security/resolver/MemberIdResolver.java
server/src/main/java/gohome/dailydaily/global/error/ExceptionCode.java
server/src/main/resources/static/docs/index.html
server/src/test/java/gohome/dailydaily/domain/member/controller/MemberControllerTest.java
server/src/test/java/gohome/dailydaily/util/TestConstant.java

어떤 종류의 PR인가요?
- Review Response > nickname, createdAt 추가
- MemberIdResolver 예외 변경

✨ feat : Review Response > nickname, createdAt, modifiedAt 추가

---

server/src/docs/asciidoc/index.adoc
server/src/main/java/gohome/dailydaily/domain/cart/controller/CartController.java
server/src/main/java/gohome/dailydaily/domain/cart/dto/ProductCartDto.java
server/src/main/java/gohome/dailydaily/domain/cart/entity/ProductCart.java
server/src/main/java/gohome/dailydaily/domain/cart/mapper/ProductCartMapper.java
server/src/main/java/gohome/dailydaily/domain/cart/service/CartService.java
server/src/main/resources/static/docs/index.html
server/src/test/java/gohome/dailydaily/domain/cart/controller/CartControllerTest.java
server/src/test/java/gohome/dailydaily/domain/cart/service/CartServiceTest.java
server/src/test/java/gohome/dailydaily/util/TestConstant.java
server/src/test/resources/application.yml

어떤 종류의 PR인가요?
Issue Number: #10 
- 장바구니 추가 시 중복된 상품과 옵션이 존재하면 기존 장바구니 상품에 count 만 추가
- 장바구니 조회 및 수정 기능 구현 => 수정은 count 만 변경 가능
- 장바구니 조회 및 수정 Service, Controller Test 코드 구현
- 장바구니 조회 및 수정 API 문서화
-

✨ feat : 장바구니 조회 및 수정 기능 구현, API 문서화

---

server/src/main/java/gohome/dailydaily/domain/product/dto/ProductDto.java
server/src/main/java/gohome/dailydaily/domain/product/mapper/ProductMapper.java
server/src/test/java/gohome/dailydaily/domain/product/controller/ProductControllerTest.java
server/src/test/java/gohome/dailydaily/util/TestConstant.java

어떤 종류의 PR인가요?
- product Content 응답 타입을 List<String> 으로 변경
-

🐛 fix : product content 응답 수정

---

server/build.gradle
server/src/docs/asciidoc/index.adoc
server/src/main/java/gohome/dailydaily/domain/product/service/ProductService.java
server/src/main/java/gohome/dailydaily/domain/search/controller/SearchController.java
server/src/main/java/gohome/dailydaily/domain/search/dto/SearchDto.java
server/src/main/java/gohome/dailydaily/domain/search/mapper/SearchMapper.java
server/src/main/java/gohome/dailydaily/domain/search/repository/SearchRedisRepository.java
server/src/main/java/gohome/dailydaily/global/config/EmbeddedRedisConfig.java
server/src/main/java/gohome/dailydaily/global/config/RedisRepositoryConfig.java
server/src/test/java/gohome/dailydaily/domain/search/controller/SearchControllerTest.java

어떤 종류의 PR인가요?
- 인기 검색어 API 구현
- 레디스 설정 완료
- 기록 삭제 기능 필요

✨ feat : 인기 검색어 API 구현

---

server/src/main/java/gohome/dailydaily/global/config/EmbeddedRedisConfig.java
server/src/main/java/gohome/dailydaily/global/config/RedisRepositoryConfig.java
server/src/main/resources/application-server.yml

어떤 종류의 PR인가요?
- Redis Setting 수정
-

:green_heart: chore : Redis Setting 수정

---

server/src/docs/asciidoc/index.adoc
server/src/main/java/gohome/dailydaily/global/common/security/dto/LoginDto.java
server/src/main/java/gohome/dailydaily/global/common/security/filter/JwtAuthenticationFilter.java
server/src/main/java/gohome/dailydaily/global/common/security/service/AuthService.java
server/src/main/java/gohome/dailydaily/global/common/security/util/JwtTokenizer.java
server/src/main/resources/application.yml
server/src/test/java/gohome/dailydaily/global/common/security/controller/LoginControllerTest.java
server/src/test/java/gohome/dailydaily/util/TestConstant.java
server/src/test/resources/application.yml

어떤 종류의 PR인가요?
- 로그인 - 상태 유지
- 게스트 - 로그인 권한, 아이디 수정
- 로그인 API 문서 생성

✨ feat : 로그인 - 상태 유지 추가 / 게스트 로그인 - 권한, 아이디 수정

---

server/src/main/java/gohome/dailydaily/global/common/security/controller/AuthController.java
server/src/main/java/gohome/dailydaily/global/common/security/filter/JwtVerificationFilter.java
server/src/main/java/gohome/dailydaily/global/common/security/service/AuthService.java
server/src/main/java/gohome/dailydaily/global/common/security/util/JwtTokenizer.java
server/src/test/java/gohome/dailydaily/global/common/security/controller/AuthControllerTest.java

어떤 종류의 PR인가요?
- Guest 로그인 RefreshToken 추가
- Guest 로그인 테스트 코드 수정
- JwtVerificationFilter @SuppressWarnings 추가

✨ feat : Guest 로그인 RefreshToken 추가

---

server/src/docs/asciidoc/index.adoc
server/src/main/java/gohome/dailydaily/domain/member/controller/MemberController.java
server/src/main/java/gohome/dailydaily/domain/product/entity/Product.java
server/src/main/java/gohome/dailydaily/domain/review/controller/ReviewController.java
server/src/main/java/gohome/dailydaily/domain/review/dto/ReviewDto.java
server/src/main/java/gohome/dailydaily/domain/review/entity/Review.java
server/src/main/java/gohome/dailydaily/domain/review/mapper/ReviewMapper.java
server/src/main/java/gohome/dailydaily/domain/review/service/ReviewService.java
server/src/main/resources/application-server.yml
server/src/main/resources/application.yml
server/src/test/java/gohome/dailydaily/domain/member/controller/MemberControllerTest.java
server/src/test/java/gohome/dailydaily/domain/review/controller/ReviewControllerTest.java
server/src/test/java/gohome/dailydaily/util/TestConstant.java

어떤 종류의 PR인가요?
- Review 사진 등록 기능
-

✨ feat : Review 사진 등록 기능 구현

---

server/src/main/java/gohome/dailydaily/domain/cart/dto/ProductCartDto.java
server/src/main/java/gohome/dailydaily/domain/cart/mapper/ProductCartMapper.java
server/src/main/java/gohome/dailydaily/domain/order/dto/OrderDto.java
server/src/main/java/gohome/dailydaily/domain/order/dto/OrderProductDto.java
server/src/main/java/gohome/dailydaily/domain/order/mapper/OrderMapper.java
server/src/main/resources/application-server.yml
server/src/test/java/gohome/dailydaily/domain/order/controller/OrderControllerTest.java
server/src/test/java/gohome/dailydaily/util/TestConstant.java
server/src/test/resources/application.yml

어떤 종류의 PR인가요?
1. 주문생성 응답 -> oderId 를 주문번호 6자리로 전달
2. 장바구니 조회 -> optionId 전달
3. 주문 전체 조회 => 주문 생성시간 전달
-

🐛 fix: 주문, 장바구니 API 응답 수정

---

server/src/docs/asciidoc/index.adoc
server/src/main/java/gohome/dailydaily/domain/order/dto/OrderDto.java
server/src/main/java/gohome/dailydaily/domain/order/mapper/OrderMapper.java
server/src/test/java/gohome/dailydaily/domain/order/controller/OrderControllerTest.java
server/src/test/java/gohome/dailydaily/domain/order/service/OrderServiceTest.java
server/src/test/java/gohome/dailydaily/util/TestConstant.java

어떤 종류의 PR인가요?
- OrderServiceTest 오류 수정
- 주문 응답으로 주문번호 전달
-

🐛 fix : Order Test 및 주문번호 수정

---

server/src/main/java/gohome/dailydaily/domain/like/repository/LikeRepository.java
server/src/main/java/gohome/dailydaily/domain/like/service/LikeService.java
server/src/main/java/gohome/dailydaily/domain/member/controller/MemberController.java
server/src/main/java/gohome/dailydaily/domain/product/dto/CategoryGetDto.java
server/src/main/java/gohome/dailydaily/domain/product/mapper/ProductMapper.java
server/src/main/java/gohome/dailydaily/domain/product/service/ProductService.java
server/src/main/java/gohome/dailydaily/global/error/ExceptionCode.java
server/src/test/java/gohome/dailydaily/domain/member/controller/MemberControllerTest.java

어떤 종류의 PR인가요?
- 좋아요 Post 중복 검사
- 좋아요 상품조회 에러 해결
-

🐞bug: 좋아요 조회 및 삭제 오류 해결

---

server/src/main/java/gohome/dailydaily/domain/cart/service/CartService.java
server/src/main/java/gohome/dailydaily/domain/order/controller/OrderController.java
server/src/main/java/gohome/dailydaily/domain/order/dto/OrderDto.java
server/src/main/java/gohome/dailydaily/domain/order/dto/OrderProductDto.java
server/src/main/java/gohome/dailydaily/domain/order/entity/OrderProduct.java
server/src/main/java/gohome/dailydaily/domain/order/service/OrderService.java
server/src/main/java/gohome/dailydaily/domain/search/controller/SearchController.java
server/src/main/java/gohome/dailydaily/domain/search/repository/SearchRedisRepository.java
server/src/main/java/gohome/dailydaily/global/config/EmbeddedRedisConfig.java

어떤 종류의 PR인가요?
- 장바구니에서 상품 주문 시 해당 상품을 장바구니에서 삭제
-

🐞fix: 주문 생성시 장바구니 상품 삭제
